# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ic_parList <- function(R_parList) {
    .Call('icenReg_ic_parList', PACKAGE = 'icenReg', R_parList)
}

R_ic_bayes <- function(R_bayesList, priorFxn, R_ic_parList) {
    .Call('icenReg_R_ic_bayes', PACKAGE = 'icenReg', R_bayesList, priorFxn, R_ic_parList)
}

