// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// ic_parList
Rcpp::List ic_parList(Rcpp::List R_parList);
RcppExport SEXP icenReg_ic_parList(SEXP R_parListSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type R_parList(R_parListSEXP);
    __result = Rcpp::wrap(ic_parList(R_parList));
    return __result;
END_RCPP
}
// R_ic_bayes
Rcpp::List R_ic_bayes(Rcpp::List R_bayesList, Rcpp::Function priorFxn, Rcpp::List R_ic_parList);
RcppExport SEXP icenReg_R_ic_bayes(SEXP R_bayesListSEXP, SEXP priorFxnSEXP, SEXP R_ic_parListSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type R_bayesList(R_bayesListSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type priorFxn(priorFxnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type R_ic_parList(R_ic_parListSEXP);
    __result = Rcpp::wrap(R_ic_bayes(R_bayesList, priorFxn, R_ic_parList));
    return __result;
END_RCPP
}
