// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// ic_parList
Rcpp::List ic_parList(Rcpp::List R_parList);
RcppExport SEXP icenReg_ic_parList(SEXP R_parListSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type R_parList(R_parListSEXP);
    __result = Rcpp::wrap(ic_parList(R_parList));
    return __result;
END_RCPP
}
